### PR TITLE
Improve: adding mongodb service and update docker guide

### PR DESCRIPTION
**Pull request by FranciscoJBrito**
#### Improvements

- Adding the mongodb service to the compose, additionally add an ENV_FILE ARG in the Dockerfile, in case we later have a compose for development and another for production.
- Adding extra step to set the environment variable needed to run mongodb.
- Changing the execution of the frontend to production mode, for better performance.

---
#### Test cases

- [x]  Register a new user
- [x]  Login
- [x]  Create a new organization
- [x]  Create a new project
- [x]  Create a new task
- [x]  Update task's status, dueDate, ...
- [x]  Create new project's view
- [x]  Adding new member to organization
- [x]  Adding new member to project

---

REF: #190

### CODE REVIEW

**Comment by hudy9x** [comment]
@namnn9x  could you please review this pr ?

**Comment by namnn9x** [comment]
> this
ok,i will check it

**Comment by hudy9x** [comment]
@FranciscoJBrito , @namnn9x 
There's some testcases you guys are supposed to check before merging:
- Register a new user
- Login
- Create a new organization
- Create a new project
- Create a new task
- Update task's status, dueDate, ...
- Create new project's view
- Adding new member to organization
- Adding new member to project

**Comment by FranciscoJBrito** [comment]
@hudy9x, @namnn9x I changed the frontend execution to production mode because the performance in development mode was terrible. On the other hand, separate the entry points for the backend and frontend.

**Comment by hudy9x** [comment]
@FranciscoJBrito it's looking good.
@namnn9x Please help me to verify this pr. I've been reviewing your pr #202

**Comment by namnn9x** [comment]
@hudy9x @FranciscoJBrito I am implementing test. Please waitting

**Comment by namnn9x** [comment]
@FranciscoJBrito 
image
Frontend and Backend build error. Are you having the same problem ?

**Comment by namnn9x** [comment]
@FranciscoJBrito I is have not exp with docker, maybe because it is not reading the path ` command: /bin/sh -c "./docker/be-entrypoint.sh && yarn backend"`  
image

**Comment by namnn9x** [comment]
@FranciscoJBrito  I cloned your code and I'm facing some issues. Here are my steps
- When I pulled the source code, I added an env.local file and the necessary environment variables.
- Then I ran docker-compose build and afterwards I executed docker-compose up -d, but an error occurred.
 I suspect the problem lies in the file paths. `command: /bin/sh -c "./docker/be-entrypoint.sh && yarn backend" . Similiar with frontend
 image

**Comment by hudy9x** [comment]
Hmm, I think you forgot to mapping folder from real machine to docker.
This was not an error if you've used WSL for running docker
Try to run docker in WSL @namnn9x 
Besides, could you add a mapping volume for Windows users who not using WSL ? @FranciscoJBrito 

It might be something like as follows I think
```
C:/Users/hp/Downloads:/data/
```

**Comment by hudy9x** [comment]
@FranciscoJBrito 
Your docker setup work well for me.
I've just set this up and built successfully 

image

However, there's a few small issues here:

**1/** I think you should turn off logging for mongodb image. It's hard to review and detect errors, ...

**2/** Build process is ok. But i can not log in or signup. Here is the error

Screenshot from 2024-06-12 21-29-05

**3/** Could your please change the default port (Ex: 6379, 3000, 27017) to another ? (Ex: 6379 -> 6377, etc...)

Because it might be caused conflicts to running ports. Someone like me use 6379 for redis, so i'm supposed to turn of redis-server before running the docker
It would be better to put these default port in another environment section (inside the docker-compose file), so anyone can change it as they want.

**4/** About the setup guide. Due to I'm running v26.1.4 for docker and v2.27.1 for compose

It requires me to run a quite different commands.
So if your version is greater than me or yours is the latest then the setup guide is ok.
If not, please update it to match the latest version
image

**Comment by FranciscoJBrito** [comment]
@namnn9x @hudy9x I don't think this is a volume issue, do you have the .sh files inside the docker folder?

**Comment by FranciscoJBrito** [comment]
sorry guys, I selected the wrong auto workflow and ended up deleting the remote branch 😅, anyway I made some changes.
1. @hudy9x the logs you were receiving were not from mongodb, they were from redis.
2. If I change the default ports, some errors occur, anyway i directly add all the ports and variables in the docker-compose, they are configurable.
3. I update the configuration guide, modifying the `docker-compose` commands to the correct version, which is `docker compose`.

**Comment by FranciscoJBrito** [comment]
@hudy9x  got u, I added a modification to the mongodb url, try now please. If you made any port changes to something additional, let me know, on the other hand remember that the `.env.local` can interfere if the `MONGODB_URL` and `REDIS_HOST` variables have any value.

**Comment by hudy9x** [comment]
@FranciscoJBrito ok, I'm gonna try it now

**Comment by hudy9x** [comment]
well done @FranciscoJBrito 
work like a charm :)))
and extremely fast
Screenshot from 2024-06-13 23-29-53

**Pull request merged**
